### ISSUE TITLE
pyRORPO

### ISSUE THREAD

**Issue by marioviti** [path-openings/RORPO#12]
Hi!
I've some troubles with the pyRORPO bindings.
I was able to import by typing import pyRORPO
How do you use the bindings? can you give an example using a 3d numpy array?

Thanks!

**Comment by Tarkof** [comment]
Hello marioviti,

We don't have an official documentation for the bindings yet.

For the moment you can take a look to [this](https://colab.research.google.com/drive/1848Fwaqgkagjv5AuRHplRVW7SYLCtU8e?usp=sharing) colab notebook.
It has example for each method available in pyRORPO.

If there is something missing don't hesitate to ask :)

**Comment by Tarkof** [comment]
Do you import inside `/build/pyRORPO` directory ?

**Comment by marioviti** [comment]
Ohhhh I see
I imported from the pyRORPO and python was just importing the directory as a package !
I see now! thanks a lot!

**Comment by Tarkof** [comment]
No worries! Someone on my team had the same issue this morning.
I might change the name of the package to avoid confusion. Maybe just `RORPO`.

As for importing form somewhere else, I see a typo in your example: `pyRORPO.pyRORPO_multiscale` instead of `pyRORPO.RORPO_multiscale`. More confusion caused by the current name ...

**Comment by marioviti** [comment]
Thanks! All is working good!
